import {
  IconX,
  IconNote,
  IconListCheck,
  IconTrash,
  IconPlus,
  IconEdit,
  IconArrowLeft,
  IconArrowsMaximize,
  IconAdjustments,
  IconSettings,
  IconCheck,
  IconMessageCircle,
  IconDeviceFloppy,
  IconSend,
  IconClipboard,
  IconLink,
  IconCopy,
  IconChevronRight,
  IconAlarmOff,
  IconCalendar,
  IconList,
  IconArrowsRandom,
  IconSparkles,
  IconPlayerPlay,
  IconRobot,
  IconBrain,
  IconBook,
  IconChevronLeft,
  IconPinned,
  IconCalendarEvent,
  IconBulb,
  IconMarkdown,
  IconTypography,
  IconTable,
  IconPalette,
} from "@tabler/icons-react";

/**
 * Centralized icon map used across the app.
 * Each value is a JSX element that can be passed directly to <Button svg={...} />.
 *
 * All icons use `currentColor` so they automatically follow the parent's CSS `color`.
 */
export const SVGS = {
  close: <IconX size={20} />,
  note: <IconNote size={20} />,
  task: <IconListCheck size={20} />,
  trash: <IconTrash size={20} />,
  plus: <IconPlus size={20} />,
  edit: <IconEdit size={20} />,
  back: <IconArrowLeft size={20} />,
  expand: <IconArrowsMaximize size={20} />,
  config: <IconAdjustments size={20} />,
  gear: <IconSettings size={20} />,
  check: <IconCheck size={20} />,
  chat: <IconMessageCircle size={20} />,
  save: <IconDeviceFloppy size={20} />,
  send: <IconSend size={20} />,
  paste: <IconClipboard size={20} />,
  clip: <IconLink size={20} />,
  copy: <IconCopy size={20} />,
  go: <IconChevronRight size={20} />,
  alarmOff: <IconAlarmOff size={20} />,
  calendar: <IconCalendar size={20} />,
  list: <IconList size={20} />,
  random: <IconArrowsRandom size={20} />,
  generate: <IconSparkles size={20} />,
  play: <IconPlayerPlay size={20} />,
  robot: <IconRobot size={20} />,
  ai: <IconBrain size={20} />,
  read: <IconBook size={20} />,
  previous: <IconChevronLeft size={20} />,
  next: <IconChevronRight size={20} />,
  pin: <IconPinned size={20} />,
  calendar2: <IconCalendarEvent size={20} />,
  thought: <IconBulb size={20} />,
  markdown: <IconMarkdown size={20} />,
  text: <IconTypography size={20} />,
  table: <IconTable size={20} />,
  palette: <IconPalette size={20} />,
};
